<?php
/**
 * @file
 * @version 0.1
 * @copyright 2018 CN-Consult GmbH
 * @author Yannick Lapp <yannick.lapp@cn-consult.eu>
 */

use PHPUnit\Framework\TestCase;
use Utils\ShellExecutor;

/**
 * Checks whether the ShellExecutor class works as expected.
 * This test works because exec() and system() were overridden in testboot.php for the Utils namespace.
 */
class ShellExecutorTest extends TestCase
{
    /**
     * Checks whether the getters and setters work as expected.
     *
     * @covers \Utils\ShellExecutor::setOsname()
     * @covers \Utils\ShellExecutor::osName()
     */
    public function testCanGetAttributes()
    {
        $shellExecutor = new ShellExecutor("mytest");

        $testOsName = "The name";
        $shellExecutor->setOsname($testOsName);
        $this->assertEquals($testOsName, $shellExecutor->osName());
    }

    /**
     * Checks whether a command can be successfully executed.
     * See testboot.php for the overridden exec() function
     *
     * @covers \Utils\ShellExecutor::__construct()
     * @covers \Utils\ShellExecutor::executeCommand()
     */
    public function testCanExecuteCommand()
    {
        $shellExecutor = new ShellExecutor("win");

        $returnValue = $shellExecutor->executeCommand("hello");
        $this->assertEquals("hello", $returnValue);
    }

    /**
     * Checks whether the output can be redirected.
     *
     * @param String $_osName The os name
     * @param String $_command The command
     * @param String $_expectedCommand The expected command as generated by the ShellExecutor
     *
     * @dataProvider redirectOutputProvider()
     *
     * @covers \Utils\ShellExecutor::__construct()
     * @covers \Utils\ShellExecutor::executeCommand()
     * @covers \Utils\ShellExecutor::getOutputHideRedirect()
     */
    public function testCanRedirectOutput(String $_osName, String $_command, String $_expectedCommand)
    {
        $shellExecutor = new ShellExecutor($_osName);
        $returnValue = $shellExecutor->executeCommand($_command, true);
        $this->assertEquals($_expectedCommand, $returnValue);
    }

    /**
     * DataProvider for ShellExecutorTest::testCanRedirectOutput().
     *
     * @return array The test values in the format array(osName, command, expectedCommand)
     */
    public function redirectOutputProvider()
    {
        return array(
            "Windows" => array("win", "hello", "hello 2>NUL"),
            "Linux" => array("linux", "hello", "hello 2>/dev/null"),
            "Other" => array("other", "hello", "hello 2>output.txt")
        );
    }

    /**
     * Checks whether the screen can be cleared as expected.
     * See testboot.php for the overridden system() function
     */
    public function testCanClearScreen()
    {
        $shellExecutor = new ShellExecutor("Linux");

        $this->expectOutputString("clear");
        $shellExecutor->clearScreen();
    }
}
