language: php
php:
  - 7.1
  - 7.1.8
  - 7.1.9
  - nightly
os: linux
dist: xenial
sudo: required
install:
  - composer install
  - sudo apt-get update
  - sudo apt-get install -y ffmpeg
script: phpunit --configuration tests/phpunit.xml tests --coverage-text
